name: heig
channels:
 - defaults
 - conda-forge
dependencies:
 - python=3.11
 - numpy=1.26.4
 - pandas=2.2.2
 - nibabel=5.2.1
 - scipy=1.11.4
 - sklearn=1.4.2
 - bitarray=2.9.2
 - h5py=3.11.0
 - numexpr=2.10.0
